# Generated by Django 3.0.5 on 2020-05-01 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('ship_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('destination', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shipping Order',
            },
        ),
    ]
